version: '3'

services:

  app:
    container_name: app
    build: .docker
    restart: always
    volumes:
      - ./application:/application

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    container_name: nginx
    working_dir: /application
    volumes:
        - ./application:/application
        - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - /log-nginx:/var/log/nginx
    ports:
     - "$HTTP_PORT:80"
    depends_on:
      - app
      - postgres

  postgres:
    image: postgres:11.1-alpine
    container_name: pgsql
    ports:
      - $DB_PORT:5432
    volumes:
      - /database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD

networks:
  default:
    driver: bridge

